#ifndef RAYCLI_EXTENSION_RAYUTILS_DIAGNOSTICS_LOG_H
#define RAYCLI_EXTENSION_RAYUTILS_DIAGNOSTICS_LOG_H

#include <rayutils/diagnostics/log.h>

#define RAYCLI_LOG_CMDLINE(options, code, file, column, message_format, ...) \
	ray_log(((code) << 16) | (options) | RAY_LOG_METADATA_OPTION_INTERNAL, file, (RaySpan) { .stream = "command line", .function = NULL, .line = 1, column }, message_format, __VA_ARGS__)

/* Metadata */
/* Systems */
enum {
	RAYCLI_LOG_METADATA_CODE_SYS_CMDLINE = RAY_LOG_METADATA_CODE_SYS_CUSTOM,
};

/* Categories */
/* Cmdline categories */
enum {
	RAYCLI_LOG_METADATA_CODE_CAT_CMDLINE_IO = RAY_LOG_METADATA_CODE_CAT_CUSTOM,
	RAYCLI_LOG_METADATA_CODE_CAT_CMDLINE_LEX,
	RAYCLI_LOG_METADATA_CODE_CAT_CMDLINE_PAR,
};

/* Reasons */
/* Cmdline reasons */
enum {
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_INSARGV,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_INVARG,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_FOPEN,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_UNKCMD,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_EMPTIDEN,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_LNGSHRTOPT,
	RAYCLI_LOG_METADATA_CODE_REA_CMDLINE_UNEXPTOK,
};

#endif /* RAYCLI_EXTENSION_RAYUTILS_DIAGNOSTICS_LOG_H */
